### ISSUE TITLE
Failed to enable this extension

### ISSUE THREAD

**Issue by g-plane** [misolori/vscode-fluent-icons#17] opened 2021-06-02 01:45 UTC
**Describe the bug**
This extension can't be enabled.

**Expected behavior**
Enable extension successfully without any errors and update VS Code product icons.

**Screenshots**

![图片](https://user-images.githubusercontent.com/17216317/120411246-0d88c300-c387-11eb-8879-ec34006f6e01.png)

**Additional context**
Nothing.

**Comment by misolori** [comment] 2021-06-02 03:24
Can you please provide more information about the error? Platform, versions, etc?

**Comment by g-plane** [comment] 2021-06-02 03:38
VS Code version: 1.56.2
OS: Linux x64 5.12.8-arch1-1
Extension version: 0.0.12

**Comment by misolori** [comment] 2021-06-02 04:49
Can you try reloading the applications and trying again? If it still persist can you open developer tools from the command palette (cmd/ctrl+shift+p) and paste a screenshot of the output?

**Comment by g-plane** [comment] 2021-06-02 05:36
I've reloaded many times and even re-install the extension, but it still doesn't work.

**Comment by misolori** [comment] 2021-06-02 13:58
Can you open dev tools and paste the output after trying to install again?

**Comment by g-plane** [comment] 2021-06-02 14:29
![图片](https://user-images.githubusercontent.com/17216317/120498546-e1565c00-c3f1-11eb-9367-7a2af93485cf.png)

**Comment by misolori** [comment] 2021-06-02 14:39
This is really strange, I recently removed the [extensionKind property](https://github.com/misolori/vscode-fluent-icons/commit/cdfc0e4d9ca82ecc269cab27f0597f9242a9c90a) but shouldn't affect the extension. I can't reproduce the error, let me ask in the vscode repo.

**Comment by misolori** [comment] 2021-06-02 14:44
There's a chance the theme file got corrupted when updating, can you try removing the theme file from disk following:

1. Close VS Code
2. run `rm -r ~/.vscode/extensions/miguelsolorio.fluent-icons-0.0.12` from the terminal
3. Load VS Code and re-install extension

**Comment by g-plane** [comment] 2021-06-02 14:49
It works. Should I close this issue?

**Comment by misolori** [comment] 2021-06-02 15:11
Awesome, thanks for trying that out! I'll go ahead and close it out. Thanks again!

**Closed by misolori** 2021-06-02 15:11 UTC
Labels: bug, upstream
